apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
  namespace: devops
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      nodePort: 30089
  type: NodePort
